In [84]:
import numpy as np
import pandas as pd

In [100]:
data = pd.read_csv("Single_data.csv")
data.head()

Unnamed: 0  AnalogValue  Density  Amplitude  Result
0           0          587      579       0.72       0
1           1          589      592       0.72       0
2           2          605      603       0.74       0
3           3          624      627       0.76       0
4           4          622      622       0.76       0

In [101]:
data = data.drop("Unnamed: 0", axis = 1)

In [102]:
data['Result'] = data['Result'].replace({2: 0, 3: 1})

data.head()


AnalogValue  Density  Amplitude  Result
0          587      579       0.72       0
1          589      592       0.72       0
2          605      603       0.74       0
3          624      627       0.76       0
4          622      622       0.76       0

In [103]:
X = data.iloc[200:400, :-1]
y = data.iloc[200:400, -1]

In [104]:
X.head()

AnalogValue  Density  Amplitude
200          396      396       0.48
201          405      407       0.49
202          423      423       0.52
203          413      411       0.50
204          405      402       0.49

In [105]:
y.head()

200    0
201    0
202    0
203    0
204    0
Name: Result, dtype: int64

In [106]:
X = X.reset_index(drop = True)
X.tail()

AnalogValue  Density  Amplitude
195          656      663       0.80
196          671      672       0.82
197          675      669       0.82
198          678      676       0.83
199          677      679       0.83

In [107]:
y = y.reset_index(drop = True)
y.tail()

195    1
196    1
197    1
198    1
199    1
Name: Result, dtype: int64

In [108]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
 

In [109]:
# from keras.utils import to_categorical
# y = to_categorical(y)
# print(y.shape)

In [110]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [111]:
# from sklearn.preprocessing import MinMaxScaler

# # Create an instance of the MinMaxScaler
# scaler = MinMaxScaler()

# # Fit the scaler on your training data
# scaler.fit(X_train)

# # Apply the scaling transformation to your training data
# X_train_scaled = scaler.transform(X_train)

# # Apply the same scaling transformation to your test data
# X_test_scaled = scaler.transform(X_test)


In [112]:
# # from keras.utils import to_categorical
# from keras.utils import to_categorical

# # Convert y_train to one-hot encoded format
# y_train = to_categorical(y_train)
# y_test = to_categorical(y_test)

# # Check the shape
# print(y_train.shape)



In [113]:
print("Shape of the X_train:", X_train.shape)
print("Shape of the y_train:", y_train.shape)
print("Shape of the X_test:", X_test.shape)
print("Shape of the y_test:", y_test.shape)

Shape of the X_train: (160, 3)
Shape of the y_train: (160,)
Shape of the X_test: (40, 3)
Shape of the y_test: (40,)


In [114]:

X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))



In [115]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense, Conv1D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy

model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, activation='relu', input_shape=(3,1)))

# model.add(Conv1D(filters=32, kernel_size=3, activation='relu'))

model.add(LSTM(units=64, return_sequences=True))
model.add(Dropout(0.2))

model.add(LSTM(units=64, return_sequences=True))
model.add(Dropout(0.2))

model.add(Dense(units=128, activation='relu'))

model.add(Dense(units=64, activation='relu'))

model.add(Dense(units=1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_3 (Conv1D)           (None, 1, 32)             128       
                                                                 
 lstm_6 (LSTM)               (None, 1, 64)             24832     
                                                                 
 dropout_6 (Dropout)         (None, 1, 64)             0         
                                                                 
 lstm_7 (LSTM)               (None, 1, 64)             33024     
                                                                 
 dropout_7 (Dropout)         (None, 1, 64)             0         
                                                                 
 dense_9 (Dense)             (None, 1, 128)            8320      
                                                                 
 dense_10 (Dense)            (None, 1, 64)            

In [116]:
from keras.callbacks import EarlyStopping

# Create the EarlyStopping callback
early_stopping = EarlyStopping(monitor='accuracy', patience=5)

NameError: name 'y_train' is not defined

In [118]:
model.fit(X_train , y_train, epochs = 20)

Epoch 1/20
5/5 [==============================] - 5s 7ms/step - loss: 0.6929 - accuracy: 0.5063
Epoch 2/20
5/5 [==============================] - 0s 8ms/step - loss: 0.6918 - accuracy: 0.5250
Epoch 3/20
5/5 [==============================] - 0s 9ms/step - loss: 0.6901 - accuracy: 0.5250
Epoch 4/20
5/5 [==============================] - 0s 7ms/step - loss: 0.6875 - accuracy: 0.5250
Epoch 5/20
5/5 [==============================] - 0s 7ms/step - loss: 0.6811 - accuracy: 0.5437
Epoch 6/20
5/5 [==============================] - 0s 8ms/step - loss: 0.6685 - accuracy: 0.6375
Epoch 7/20
5/5 [==============================] - 0s 14ms/step - loss: 0.6505 - accuracy: 0.7312
Epoch 8/20
5/5 [==============================] - 0s 7ms/step - loss: 0.6112 - accuracy: 0.8313
Epoch 9/20
5/5 [==============================] - 0s 7ms/step - loss: 0.5595 - accuracy: 0.8438
Epoch 10/20
5/5 [==============================] - 0s 7ms/step - loss: 0.4801 - accuracy: 0.8938
Epoch 11/20
5/5 [=====================

In [127]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 2s 10ms/step - loss: 0.0307 - accuracy: 1.0000


[0.030726373195648193, 1.0]

In [126]:
y_test

90     0
72     0
155    1
134    1
128    1
105    1
77     0
75     0
58     0
76     0
102    1
97     0
70     0
52     0
36     0
43     0
18     0
94     0
103    1
31     0
171    1
69     0
67     0
64     0
12     0
47     0
121    1
126    1
10     0
141    1
148    1
85     0
143    1
33     0
116    1
101    1
39     0
162    1
44     0
154    1
Name: Result, dtype: int64

In [82]:
import numpy as np

# Assuming y_pred contains the predicted values
y_pred_binary = np.argmax(y_pred, axis=1)
# predicted_labels_original = np.argmax(y_pred_binary, axis=1)

# Print the binary predictions
print(y_pred_binary)


[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [52]:
y_test.shape

(40, 1, 2)

In [55]:
y_pred_binary.shape

(40, 2)

In [54]:
y_test = y_test[:, 0]
y_test.shape

(40, 2)

In [56]:
y_pred_binary

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [57]:
y_test

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [ ]:
y_test = y_test.astype("int64")

In [ ]:
y_test

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix

# Reshape y_test
# y_test_reshaped = np.reshape(y_test, (y_test.shape[0], y_test.shape[2]))

# Convert y_pred_binary to 1D array
# predicted_labels = np.squeeze(y_pred_binary)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_binary)
print("Accuracy:", accuracy)

# Compute confusion matrix
cm = confusion_matrix(y_test, y_pred_binary)
print("Confusion Matrix:")
print(cm)


In [ ]:
rig_lef = pd.read_csv("left1.csv")

In [ ]:
rig_lef.head()

In [ ]:
rig_lef = rig_lef.drop("Unnamed: 0", axis = 1)
rig_lef.head()

In [ ]:
X = rig_lef.iloc[50:60, :-1]
X.head()

In [ ]:
X = X.reset_index(drop= True)
X.head()

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)


In [ ]:
print(X.shape)

In [ ]:
X = np.reshape(X, (X.shape[0], X.shape[1], 1))
X.shape

In [ ]:
y_pred = model.predict(X)

In [ ]:
y_pred_binary = np.argmax(y_pred, axis=2)

# Print the binary predictions
print(y_pred_binary)