In [115]:
import pandas as pd
import numpy as np

In [116]:
data = pd.read_csv("new_upper_down.csv")

In [117]:
# data = data.drop("Unnamed: 0", axis = 1)

In [118]:
data.head()

AnalogValue  Density  Amplitude  Result
0          881      887       1.08       0
1          909      903       1.11       0
2          889      890       1.09       0
3          898      903       1.10       0
4          901      898       1.10       0

In [119]:
data.tail()

AnalogValue  Density  Amplitude  Result
3995          971      972       1.19       1
3996          976      974       1.19       1
3997          988      989       1.21       1
3998          995      990       1.21       1
3999          987      977       1.21       1

In [120]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]


In [121]:
X.head()

AnalogValue  Density  Amplitude
0          881      887       1.08
1          909      903       1.11
2          889      890       1.09
3          898      903       1.10
4          901      898       1.10

In [122]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Result, dtype: int64

In [123]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)


In [124]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [125]:
# # from keras.utils import to_categorical
# from keras.utils import to_categorical

# # Convert y_train to one-hot encoded format
# y_train = to_categorical(y_train)
# y_test = to_categorical(y_test)

# # Check the shape
# print(y_train.shape)

In [126]:
print("Shape of the X_train:", X_train.shape)
print("Shape of the y_train:", y_train.shape)
print("Shape of the X_test:", X_test.shape)
print("Shape of the y_test:", y_test.shape)

Shape of the X_train: (3200, 3)
Shape of the y_train: (3200,)
Shape of the X_test: (800, 3)
Shape of the y_test: (800,)


In [109]:

X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))


In [110]:
print("Shape of the X_train:", X_train.shape)
print("Shape of the y_train:", y_train.shape)
print("Shape of the X_test:", X_test.shape)
print("Shape of the y_test:", y_test.shape)

Shape of the X_train: (3200, 3, 1)
Shape of the y_train: (3200,)
Shape of the X_test: (800, 3, 1)
Shape of the y_test: (800,)


In [111]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense, Conv1D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy

model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, activation='relu', input_shape=(3,1)))

# model.add(Conv1D(filters=32, kernel_size=3, activation='relu'))

model.add(LSTM(units=64, return_sequences=True))
model.add(Dropout(0.2))

model.add(LSTM(units=64, return_sequences=True))
model.add(Dropout(0.2))

model.add(Dense(units=128, activation='relu'))

model.add(Dense(units=64, activation='relu'))

model.add(Dense(units=1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()


Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_10 (Conv1D)          (None, 1, 32)             128       
                                                                 
 lstm_20 (LSTM)              (None, 1, 64)             24832     
                                                                 
 dropout_20 (Dropout)        (None, 1, 64)             0         
                                                                 
 lstm_21 (LSTM)              (None, 1, 64)             33024     
                                                                 
 dropout_21 (Dropout)        (None, 1, 64)             0         
                                                                 
 dense_30 (Dense)            (None, 1, 128)            8320      
                                                                 
 dense_31 (Dense)            (None, 1, 64)           

In [112]:
from keras.callbacks import EarlyStopping

# Create the EarlyStopping callback
early_stopping = EarlyStopping(monitor='accuracy', patience=5)

In [113]:


# y_train = np.reshape(y_train, (y_train.shape[0],1,2))

# y_test = np.reshape(y_test, (y_test.shape[0],1, 2))
y_train.shape


(3200,)

In [114]:
model.fit(X_train , y_train, epochs = 100, callbacks = [early_stopping])

Epoch 1/100
100/100 [==============================] - 5s 6ms/step - loss: 0.6851 - accuracy: 0.5553
Epoch 2/100
100/100 [==============================] - 1s 5ms/step - loss: 0.6375 - accuracy: 0.6075
Epoch 3/100
100/100 [==============================] - 1s 5ms/step - loss: 0.6280 - accuracy: 0.6022
Epoch 4/100
100/100 [==============================] - 1s 5ms/step - loss: 0.6230 - accuracy: 0.6037
Epoch 5/100
100/100 [==============================] - 1s 5ms/step - loss: 0.6192 - accuracy: 0.6094
Epoch 6/100
100/100 [==============================] - 1s 5ms/step - loss: 0.6086 - accuracy: 0.6225
Epoch 7/100
100/100 [==============================] - 1s 6ms/step - loss: 0.6081 - accuracy: 0.6169
Epoch 8/100
100/100 [==============================] - 1s 6ms/step - loss: 0.5976 - accuracy: 0.6294
Epoch 9/100
100/100 [==============================] - 1s 6ms/step - loss: 0.5940 - accuracy: 0.6244
Epoch 10/100
100/100 [==============================] - 1s 6ms/step - loss: 0.5959 - accura

In [28]:
model.predict(X_test)

2/2 [==============================] - 1s 4ms/step


array([[[0.00804536]],

       [[0.5508642 ]],

       [[0.00551351]],

       [[0.9997393 ]],

       [[1.        ]],

       [[1.        ]],

       [[0.00276213]],

       [[0.99943507]],

       [[0.9996854 ]],

       [[0.00277963]],

       [[0.00273408]],

       [[0.99998415]],

       [[0.9992187 ]],

       [[0.0027525 ]],

       [[0.9999331 ]],

       [[0.99969023]],

       [[0.00275399]],

       [[0.9999251 ]],

       [[0.00276469]],

       [[0.00273283]],

       [[1.        ]],

       [[0.31682548]],

       [[0.99999243]],

       [[0.00282698]],

       [[0.00273433]],

       [[0.00274414]],

       [[0.00274987]],

       [[0.00272201]],

       [[0.99999994]],

       [[0.99999934]],

       [[0.24022801]],

       [[0.10011062]],

       [[0.00274805]],

       [[0.00276892]],

       [[0.99997765]],

       [[0.9999999 ]],

       [[0.99999964]],

       [[0.99999994]],

       [[0.99916816]],

       [[0.00276422]]], dtype=float32)

In [19]:
y_test

95     0
15     0
30     0
158    1
128    1
115    1
69     0
170    1
174    1
45     0
66     0
182    1
165    1
78     0
186    1
177    1
56     0
152    1
82     0
68     0
124    1
16     0
148    1
93     0
65     0
60     0
84     0
67     0
125    1
132    1
9      0
18     0
55     0
75     0
150    1
104    1
135    1
137    1
164    1
76     0
Name: Result, dtype: int64

In [30]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 2s 8ms/step - loss: 0.0405 - accuracy: 0.9750


[0.04049764573574066, 0.9750000238418579]

In [102]:
y_test.shape

(40, 1, 2)

In [103]:
y_test = y_test[:,0]
y_test.shape

(40, 2)

In [104]:
y_test = y_test[:,0]
y_test.shape

(40,)

In [114]:
y_pred_decoded.shape

(40, 2)

In [106]:
y_pred_decoded = y_pred_decoded[:,0]
y_pred_decoded.shape

(40,)

In [112]:
y_pred_decoded

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [113]:
y_test

array([1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1.,
       0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 1.], dtype=float32)

In [127]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier


In [128]:
svm_model = SVC()  # For SVM
tree_model = DecisionTreeClassifier()  # For Decision Tree


In [129]:
svm_model.fit(X_train, y_train)  # X_train is the training data, y_train is the corresponding labels
tree_model.fit(X_train, y_train)


DecisionTreeClassifier()

In [130]:
svm_predictions = svm_model.predict(X_test)  # X_test is the test data
tree_predictions = tree_model.predict(X_test)


In [131]:
from sklearn.metrics import accuracy_score

svm_accuracy = accuracy_score(y_test, svm_predictions)  # y_test is the true labels for the test data
tree_accuracy = accuracy_score(y_test, tree_predictions)


In [132]:
svm_accuracy

0.62625

In [133]:
tree_accuracy

0.69875

In [135]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train)
  
# accuracy on X_test
accuracy = knn.score(X_test, y_test)
print(accuracy)

0.665


In [136]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_train, y_train)
gnb_predictions = gnb.predict(X_test)
  
# accuracy on X_test
accuracy = gnb.score(X_test, y_test)
print(accuracy)

0.6175
